-- =============================================
-- STEP 1: Enum 타입 정의
-- =============================================

-- 알림 타입
CREATE TYPE notification_type AS ENUM (
  'ALIMTALK',           -- 카카오 알림톡
  'CONSULT_REQUEST'     -- 상담 신청
);

-- 알림톡 발송 상태
CREATE TYPE alimtalk_status AS ENUM (
  'PENDING',            -- 발송 대기 (예약 발송)
  'SENT',               -- 발송 성공
  'FAILED'              -- 발송 실패
);

-- 상담 신청 상태
CREATE TYPE consult_status AS ENUM (
  'WAITING',            -- 상담 대기
  'COMPLETED'           -- 상담 완료
);

-- 상담 등록 결과
CREATE TYPE consult_result AS ENUM (
  'SUCCESS',            -- 등록 성공
  'FAILED'              -- 등록 실패
);

-- 발송 모드
CREATE TYPE send_mode AS ENUM (
  'TEST',               -- 테스트 모드
  'LIVE'                -- 실제 발송
);

-- 템플릿 채널
CREATE TYPE template_channel AS ENUM (
  'ALIMTALK'            -- 카카오 알림톡
);

-- 템플릿 상태
CREATE TYPE template_status AS ENUM (
  'ACTIVE',             -- 사용 중
  'INACTIVE'            -- 미사용
);

-- 발송 타이밍
CREATE TYPE send_timing AS ENUM (
  'IMMEDIATE',          -- 즉시 발송
  'SCHEDULED'           -- 예약 발송
);

-- =============================================
-- STEP 1: notifications 테이블
-- =============================================

CREATE TABLE notifications (
  -- 기본 식별자
  notification_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id       UUID NOT NULL REFERENCES organizations(organization_id) ON DELETE CASCADE,

  -- 알림 타입 (핵심 분류)
  type                  notification_type NOT NULL,

  -- 대상자 정보
  recipient_phone       TEXT NOT NULL,                    -- 수신자 전화번호
  recipient_name        TEXT,                             -- 수신자 이름
  recipient_profile_id  UUID REFERENCES profiles(profile_id) ON DELETE SET NULL,  -- 회원인 경우

  -- 발신자/트리거 정보
  sender_profile_id     UUID REFERENCES profiles(profile_id) ON DELETE SET NULL,  -- 발송 트리거한 사용자

  -- ===== 알림톡(ALIMTALK) 전용 필드 =====
  alimtalk_status       alimtalk_status,                  -- 발송 상태
  alimtalk_template_code TEXT,                            -- 카카오 템플릿 코드
  alimtalk_variables    JSONB,                            -- 템플릿 변수
  alimtalk_message_id   TEXT,                             -- Solapi 메시지 ID
  alimtalk_error_code   TEXT,                             -- 실패 시 에러 코드
  alimtalk_error_message TEXT,                            -- 실패 시 에러 메시지
  alimtalk_sent_at      TIMESTAMPTZ,                      -- 실제 발송 시간
  send_mode             send_mode,                        -- TEST / LIVE

  -- ===== 상담 신청(CONSULT_REQUEST) 전용 필드 =====
  consult_status        consult_status,                   -- 상담 상태 (대기/완료)
  consult_result        consult_result,                   -- 등록 결과 (성공/실패)
  consult_notes         TEXT,                             -- 관리자 메모
  consult_message       TEXT,                             -- 상담 신청 메시지
  consult_completed_at  TIMESTAMPTZ,                      -- 상담 완료 시간
  consult_completed_by  UUID REFERENCES profiles(profile_id) ON DELETE SET NULL,

  -- ===== 재발송 관련 =====
  parent_notification_id BIGINT REFERENCES notifications(notification_id) ON DELETE SET NULL,
  retry_count           INT DEFAULT 0,                    -- 현재 재시도 횟수

  -- ===== 연관 엔티티 =====
  schedule_id           BIGINT REFERENCES schedules(schedule_id) ON DELETE SET NULL,
  program_id            BIGINT REFERENCES programs(program_id) ON DELETE SET NULL,

  -- ===== 예약 발송 관련 (STEP 6) =====
  scheduled_send_at     TIMESTAMPTZ,                      -- 예약 발송 시간
  reminder_generated    BOOLEAN DEFAULT FALSE,            -- 리마인더 여부

  -- 타임스탬프
  created_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- notifications 인덱스
CREATE INDEX idx_notifications_org_type ON notifications(organization_id, type);
CREATE INDEX idx_notifications_org_created ON notifications(organization_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_phone ON notifications(recipient_phone);
CREATE INDEX idx_notifications_parent ON notifications(parent_notification_id) WHERE parent_notification_id IS NOT NULL;
CREATE INDEX idx_notifications_alimtalk_status ON notifications(alimtalk_status) WHERE type = 'ALIMTALK';
CREATE INDEX idx_notifications_consult_status ON notifications(consult_status) WHERE type = 'CONSULT_REQUEST';
CREATE INDEX idx_notifications_scheduled ON notifications(scheduled_send_at) WHERE alimtalk_status = 'PENDING' AND scheduled_send_at IS NOT NULL;
CREATE INDEX idx_notifications_reminder ON notifications(schedule_id, alimtalk_template_code) WHERE type = 'ALIMTALK' AND reminder_generated = TRUE;

-- notifications updated_at 트리거
CREATE TRIGGER set_notifications_updated_at
BEFORE UPDATE ON public.notifications
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- =============================================
-- STEP 4: super_templates 테이블
-- =============================================

CREATE TABLE super_templates (
  -- 기본 식별자
  super_template_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 템플릿 정보
  name                  TEXT NOT NULL,                    -- 템플릿 이름 (관리용)
  type                  TEXT NOT NULL,                    -- 템플릿 타입 (STD_BOOK_ADMIN, ADM_BOOK_STUDENT 등)
  channel               template_channel NOT NULL DEFAULT 'ALIMTALK',

  -- 카카오 알림톡 정보
  kakao_template_code   TEXT NOT NULL UNIQUE,             -- 카카오 템플릿 코드
  content               TEXT NOT NULL,                    -- 템플릿 본문 (변수 포함)

  -- 변수 메타데이터
  variables             JSONB NOT NULL DEFAULT '[]',      -- 사용 가능한 변수 목록

  -- 상태
  status                template_status NOT NULL DEFAULT 'ACTIVE',

  -- 기본 발송 설정
  default_timing        send_timing NOT NULL,             -- 기본 발송 타이밍 (즉시/예약)
  default_hours_before  INT,                              -- 예약 발송 시 기본 N시간 전 (리마인더용)

  -- 타임스탬프
  created_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- super_templates 인덱스
CREATE INDEX idx_super_templates_type ON super_templates(type);
CREATE INDEX idx_super_templates_status ON super_templates(status);

-- super_templates updated_at 트리거
CREATE TRIGGER set_super_templates_updated_at
BEFORE UPDATE ON public.super_templates
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- =============================================
-- STEP 4: organization_templates 테이블
-- =============================================

CREATE TABLE organization_templates (
  -- 기본 식별자
  org_template_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 연관 관계
  organization_id       UUID NOT NULL REFERENCES organizations(organization_id) ON DELETE CASCADE,
  super_template_id     BIGINT NOT NULL REFERENCES super_templates(super_template_id) ON DELETE CASCADE,

  -- 채널
  channel               template_channel NOT NULL DEFAULT 'ALIMTALK',

  -- 상태 (조직별로 활성화/비활성화)
  status                template_status NOT NULL DEFAULT 'ACTIVE',

  -- 발송 설정
  send_timing           send_timing NOT NULL,             -- 즉시 / 예약

  -- 리마인더 전용 (SYS_REMIND_STUDENT)
  hours_before          INT,                              -- 수업 시작 N시간 전

  -- 관리자 예약/취소 전용 (ADM_BOOK/CANCEL)
  scheduled_send_time   TIME,                             -- 일괄 발송 시간 (예: '09:00')
  batch_start_hour      INT DEFAULT 23,                   -- 배치 시작 시간 (23시부터)

  -- 타임스탬프
  created_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- 유니크 제약: 조직당 템플릿 타입 1개
  CONSTRAINT unique_org_template UNIQUE (organization_id, super_template_id)
);

-- organization_templates 인덱스
CREATE INDEX idx_org_templates_org ON organization_templates(organization_id);
CREATE INDEX idx_org_templates_super ON organization_templates(super_template_id);
CREATE INDEX idx_org_templates_status ON organization_templates(status) WHERE status = 'ACTIVE';

-- organization_templates updated_at 트리거
CREATE TRIGGER set_organization_templates_updated_at
BEFORE UPDATE ON public.organization_templates
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- =============================================
-- STEP 5: test_send_logs 테이블
-- =============================================

CREATE TABLE test_send_logs (
  log_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id       UUID REFERENCES organizations(organization_id) ON DELETE CASCADE,  -- 슈퍼어드민은 NULL
  profile_id            UUID NOT NULL REFERENCES profiles(profile_id) ON DELETE CASCADE,
  super_template_id     BIGINT NOT NULL REFERENCES super_templates(super_template_id) ON DELETE CASCADE,
  org_template_id       BIGINT REFERENCES organization_templates(org_template_id) ON DELETE SET NULL,
  recipient_phone       TEXT NOT NULL,
  sent_at               TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- test_send_logs 인덱스 (일일 사용량 조회용 - 관리자)
CREATE INDEX idx_test_send_logs_daily ON test_send_logs(organization_id, profile_id, sent_at);

-- test_send_logs 인덱스 (슈퍼어드민 로그 조회용)
CREATE INDEX idx_test_send_logs_super ON test_send_logs(profile_id, sent_at) WHERE organization_id IS NULL;

-- =============================================
-- STEP 7: in_app_notifications 테이블
-- =============================================

CREATE TABLE in_app_notifications (
  -- 기본 식별자
  in_app_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 연관 관계
  organization_id       UUID NOT NULL REFERENCES organizations(organization_id) ON DELETE CASCADE,
  notification_id       BIGINT REFERENCES notifications(notification_id) ON DELETE CASCADE,

  -- 알림 내용
  message               TEXT NOT NULL,                    -- 인앱 알림 메시지
  template_type         TEXT NOT NULL,                    -- STD_BOOK_ADMIN, STD_CANCEL_ADMIN, SYS_CONSULT_ADMIN

  -- 읽음 상태
  is_read               BOOLEAN NOT NULL DEFAULT FALSE,
  read_at               TIMESTAMPTZ,
  read_by               UUID REFERENCES profiles(profile_id) ON DELETE SET NULL,

  -- 타임스탬프
  created_at            TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- in_app_notifications 인덱스
CREATE INDEX idx_in_app_notifications_org_created ON in_app_notifications(organization_id, created_at DESC);
CREATE INDEX idx_in_app_notifications_unread ON in_app_notifications(organization_id, is_read) WHERE is_read = FALSE;

-- =============================================
-- RLS 정책: notifications
-- =============================================

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 조직 관리자: 전체 조회
CREATE POLICY "org_admin_select_notifications"
ON notifications FOR SELECT
TO authenticated
USING (is_org_admin(organization_id));

-- 조직 관리자: 상담 신청만 UPDATE 가능 (notes, status, result만)
CREATE POLICY "org_admin_update_consult_notifications"
ON notifications FOR UPDATE
TO authenticated
USING (
  is_org_admin(organization_id)
  AND type = 'CONSULT_REQUEST'
)
WITH CHECK (
  is_org_admin(organization_id)
  AND type = 'CONSULT_REQUEST'
);

-- 비회원 상담 신청 INSERT 허용 (익명)
CREATE POLICY "anon_insert_consult_notifications"
ON notifications FOR INSERT
TO anon
WITH CHECK (type = 'CONSULT_REQUEST');

-- 슈퍼어드민: 전체 접근
CREATE POLICY "super_admin_all_notifications"
ON notifications FOR ALL
TO authenticated
USING (is_super_admin());

-- =============================================
-- RLS 정책: super_templates
-- =============================================

ALTER TABLE super_templates ENABLE ROW LEVEL SECURITY;

-- 모두 조회 가능
CREATE POLICY "super_templates_select"
ON super_templates FOR SELECT
TO authenticated
USING (true);

-- 슈퍼어드민만 CUD
CREATE POLICY "super_templates_all"
ON super_templates FOR ALL
TO authenticated
USING (is_super_admin());

-- =============================================
-- RLS 정책: organization_templates
-- =============================================

ALTER TABLE organization_templates ENABLE ROW LEVEL SECURITY;

-- 조직 관리자: 본인 조직 조회
CREATE POLICY "org_templates_select"
ON organization_templates FOR SELECT
TO authenticated
USING (is_org_admin(organization_id));

-- 조직 관리자: 본인 조직 UPDATE
CREATE POLICY "org_templates_update"
ON organization_templates FOR UPDATE
TO authenticated
USING (is_org_admin(organization_id))
WITH CHECK (is_org_admin(organization_id));

-- 조직 관리자: 본인 조직 INSERT
CREATE POLICY "org_templates_insert"
ON organization_templates FOR INSERT
TO authenticated
WITH CHECK (is_org_admin(organization_id));

-- 슈퍼어드민 전체 접근
CREATE POLICY "org_templates_super_admin"
ON organization_templates FOR ALL
TO authenticated
USING (is_super_admin());

-- =============================================
-- RLS 정책: test_send_logs
-- =============================================

ALTER TABLE test_send_logs ENABLE ROW LEVEL SECURITY;

-- 조직 관리자: 본인 조직 로그 조회
CREATE POLICY "test_send_logs_select"
ON test_send_logs FOR SELECT
TO authenticated
USING (
  organization_id IS NOT NULL AND is_org_admin(organization_id)
  OR organization_id IS NULL AND is_super_admin()
);

-- 슈퍼어드민 전체 접근
CREATE POLICY "test_send_logs_super_admin"
ON test_send_logs FOR ALL
TO authenticated
USING (is_super_admin());

-- =============================================
-- RLS 정책: in_app_notifications
-- =============================================

ALTER TABLE in_app_notifications ENABLE ROW LEVEL SECURITY;

-- 조직 관리자: 본인 조직 조회
CREATE POLICY "in_app_notifications_select"
ON in_app_notifications FOR SELECT
TO authenticated
USING (is_org_admin(organization_id));

-- 조직 관리자: 본인 조직 읽음 처리
CREATE POLICY "in_app_notifications_update"
ON in_app_notifications FOR UPDATE
TO authenticated
USING (is_org_admin(organization_id))
WITH CHECK (is_org_admin(organization_id));

-- INSERT는 시스템만 (service_role)

-- 슈퍼어드민 전체 접근
CREATE POLICY "in_app_notifications_super_admin"
ON in_app_notifications FOR ALL
TO authenticated
USING (is_super_admin());

-- =============================================
-- 초기 데이터: super_templates 6종
-- =============================================

INSERT INTO super_templates (name, type, kakao_template_code, content, variables, default_timing, default_hours_before)
VALUES
  ('수강생 예약 → 관리자', 'STD_BOOK_ADMIN', 'KA_STD_BOOK_ADMIN',
   E'[수업 예약 알림]\n\n#{student_name}님이 수업을 예약하였습니다.\n\n■ 클래스: #{program_title}\n■ 일시: #{schedule_datetime}\n\n※ #{organization_name}',
   '["organization_name", "program_title", "schedule_datetime", "student_name", "student_phone"]',
   'IMMEDIATE', NULL),

  ('수강생 취소 → 관리자', 'STD_CANCEL_ADMIN', 'KA_STD_CANCEL_ADMIN',
   E'[수업 취소 알림]\n\n#{student_name}님이 수업을 취소하였습니다.\n\n■ 클래스: #{program_title}\n■ 일시: #{schedule_datetime}\n\n※ #{organization_name}',
   '["organization_name", "program_title", "schedule_datetime", "student_name", "cancel_reason"]',
   'IMMEDIATE', NULL),

  ('관리자 예약 → 수강생', 'ADM_BOOK_STUDENT', 'KA_ADM_BOOK_STUDENT',
   E'[수업 예약 안내]\n\n#{student_name}님, 수업이 예약되었습니다.\n\n■ 클래스: #{program_title}\n■ 일시: #{schedule_datetime}\n\n※ #{organization_name}',
   '["organization_name", "program_title", "schedule_datetime", "student_name", "instructor_name"]',
   'SCHEDULED', NULL),

  ('관리자 취소 → 수강생', 'ADM_CANCEL_STUDENT', 'KA_ADM_CANCEL_STUDENT',
   E'[수업 취소 안내]\n\n#{student_name}님, 예약된 수업이 취소되었습니다.\n\n■ 클래스: #{program_title}\n■ 일시: #{schedule_datetime}\n\n※ 문의사항은 학원으로 연락 부탁드립니다.\n※ #{organization_name}',
   '["organization_name", "program_title", "schedule_datetime", "student_name", "cancel_reason"]',
   'SCHEDULED', NULL),

  ('상담 신청 → 관리자', 'SYS_CONSULT_ADMIN', 'KA_SYS_CONSULT_ADMIN',
   E'[상담 신청 알림]\n\n새로운 상담 신청이 접수되었습니다.\n\n■ 신청자: #{requester_name}\n■ 연락처: #{requester_phone}\n■ 관심 클래스: #{program_title}\n■ 문의내용: #{consult_message}\n\n※ #{organization_name}',
   '["organization_name", "requester_name", "requester_phone", "program_title", "consult_message"]',
   'IMMEDIATE', NULL),

  ('수업 리마인더 → 수강생', 'SYS_REMIND_STUDENT', 'KA_SYS_REMIND_STUDENT',
   E'[수업 리마인더]\n\n#{student_name}님, 오늘 수업이 있습니다.\n\n■ 클래스: #{program_title}\n■ 일시: #{schedule_datetime}\n\n※ #{organization_name}',
   '["organization_name", "program_title", "schedule_datetime", "student_name", "instructor_name"]',
   'SCHEDULED', 24);

-- =============================================
-- Realtime 활성화: in_app_notifications
-- =============================================

ALTER PUBLICATION supabase_realtime ADD TABLE in_app_notifications;

-- =============================================
-- pgmq 큐 생성: alimtalk
-- =============================================

SELECT pgmq.create('alimtalk');

-- =============================================
-- 알림톡 발송 Trigger 함수
-- =============================================

/**
 * 수강생/관리자 예약 알림 트리거
 * - 수강생이 예약하면 관리자에게 (STD_BOOK_ADMIN) - 즉시 발송
 * - 관리자가 예약하면 수강생에게 (ADM_BOOK_STUDENT) - 하이브리드 발송
 */
CREATE OR REPLACE FUNCTION on_schedule_insert()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET SEARCH_PATH = ''
AS $$
DECLARE
  v_is_student BOOLEAN;
  v_template_type TEXT;
  v_template RECORD;
  v_recipient_phone TEXT;
  v_recipient_name TEXT;
  v_recipient_profile_id UUID;
  v_admin_phone TEXT;
  v_admin_profile_id UUID;
  v_org_name TEXT;
  v_program_title TEXT;
  v_variables JSONB;
  v_notification_id BIGINT;
  v_is_batch_period BOOLEAN;
  v_scheduled_send_at TIMESTAMPTZ;
  v_current_hour INT;
BEGIN
  -- 반복 일정 인스턴스는 원본만 처리
  IF NEW.parent_schedule_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- 예약자가 수강생인지 확인
  v_is_student := NEW.student_id = auth.uid();

  IF v_is_student THEN
    -- 수강생이 직접 예약 → 관리자에게 알림
    v_template_type := 'STD_BOOK_ADMIN';
  ELSE
    -- 관리자가 예약 → 수강생에게 알림
    v_template_type := 'ADM_BOOK_STUDENT';
  END IF;

  -- 템플릿 설정 조회
  SELECT
    st.kakao_template_code,
    st.content,
    COALESCE(ot.status, 'ACTIVE') as status,
    COALESCE(ot.send_timing, st.default_timing) as send_timing,
    COALESCE(ot.scheduled_send_time, '09:00'::TIME) as scheduled_send_time,
    COALESCE(ot.batch_start_hour, 23) as batch_start_hour
  INTO v_template
  FROM public.super_templates st
  LEFT JOIN public.organization_templates ot
    ON st.super_template_id = ot.super_template_id
    AND ot.organization_id = NEW.organization_id
  WHERE st.type = v_template_type
    AND st.status = 'ACTIVE';

  -- 템플릿이 비활성화면 스킵
  IF v_template IS NULL OR v_template.status != 'ACTIVE' THEN
    RETURN NEW;
  END IF;

  -- 조직명 조회
  SELECT name INTO v_org_name
  FROM public.organizations
  WHERE organization_id = NEW.organization_id;

  -- 프로그램명 조회
  IF NEW.program_id IS NOT NULL THEN
    SELECT title INTO v_program_title
    FROM public.programs
    WHERE program_id = NEW.program_id;
  END IF;

  IF v_is_student THEN
    -- 수강생 정보 조회 (지역 정보 포함)
    SELECT
      CASE
        WHEN region IS NOT NULL AND region != '' THEN name || '(' || region || ')'
        ELSE name
      END,
      phone
    INTO v_recipient_name, v_recipient_phone
    FROM public.profiles
    WHERE profile_id = NEW.student_id;

    -- 관리자 전화번호 조회 (첫 번째 관리자)
    SELECT p.profile_id, p.phone INTO v_admin_profile_id, v_admin_phone
    FROM public.organization_members om
    JOIN public.profiles p ON p.profile_id = om.profile_id
    WHERE om.organization_id = NEW.organization_id
      AND om.role = 'ADMIN'
      AND om.state = 'NORMAL'
      AND p.phone IS NOT NULL
    LIMIT 1;

    -- 관리자 전화번호가 없으면 스킵
    IF v_admin_phone IS NULL THEN
      RETURN NEW;
    END IF;

    -- 변수 설정
    v_variables := jsonb_build_object(
      'organization_name', v_org_name,
      'program_title', COALESCE(v_program_title, '미지정'),
      'schedule_datetime', to_char(NEW.start_time AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI'),
      'student_name', v_recipient_name,
      'student_phone', v_recipient_phone
    );

    -- notifications 생성 (즉시 발송)
    INSERT INTO public.notifications (
      organization_id, type, recipient_phone, recipient_name, recipient_profile_id,
      sender_profile_id, alimtalk_status, alimtalk_template_code, alimtalk_variables,
      schedule_id, program_id, send_mode
    ) VALUES (
      NEW.organization_id, 'ALIMTALK', v_admin_phone, NULL, v_admin_profile_id,
      NEW.student_id, 'PENDING', v_template.kakao_template_code, v_variables,
      NEW.schedule_id, NEW.program_id, 'LIVE'
    ) RETURNING notification_id INTO v_notification_id;

    -- pgmq 큐에 추가
    PERFORM pgmq.send(
      queue_name => 'alimtalk'::text,
      msg => jsonb_build_object(
        'notification_id', v_notification_id,
        'template_code', v_template.kakao_template_code,
        'recipient_phone', v_admin_phone,
        'variables', v_variables,
        'send_mode', 'LIVE',
        'is_immediate', true
      )
    );

  ELSE
    -- 관리자가 예약 → 수강생에게 알림 (하이브리드)
    -- 수강생 정보 조회
    SELECT p.name, p.phone, p.profile_id INTO v_recipient_name, v_recipient_phone, v_recipient_profile_id
    FROM public.profiles p
    WHERE p.profile_id = NEW.student_id;

    -- 수강생 전화번호가 없으면 스킵
    IF v_recipient_phone IS NULL THEN
      RETURN NEW;
    END IF;

    -- 변수 설정
    v_variables := jsonb_build_object(
      'organization_name', v_org_name,
      'program_title', COALESCE(v_program_title, '미지정'),
      'schedule_datetime', to_char(NEW.start_time AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI'),
      'student_name', v_recipient_name
    );

    -- 배치 구간 판단 (예: 23시~9시)
    v_current_hour := EXTRACT(HOUR FROM NOW() AT TIME ZONE 'Asia/Seoul');
    v_is_batch_period := (
      v_current_hour >= v_template.batch_start_hour OR
      v_current_hour < EXTRACT(HOUR FROM v_template.scheduled_send_time)
    );

    -- scheduled_send_at 계산
    IF v_is_batch_period THEN
      -- 배치 구간: 다음 발송 시간으로 설정
      IF v_current_hour >= v_template.batch_start_hour THEN
        -- 23시 이후면 다음날
        v_scheduled_send_at := (CURRENT_DATE + INTERVAL '1 day')::DATE + v_template.scheduled_send_time;
      ELSE
        -- 자정~9시면 오늘
        v_scheduled_send_at := CURRENT_DATE::DATE + v_template.scheduled_send_time;
      END IF;
    ELSE
      -- 즉시 발송 구간
      v_scheduled_send_at := NULL;
    END IF;

    -- notifications 생성
    INSERT INTO public.notifications (
      organization_id, type, recipient_phone, recipient_name, recipient_profile_id,
      sender_profile_id, alimtalk_status, alimtalk_template_code, alimtalk_variables,
      schedule_id, program_id, send_mode, scheduled_send_at
    ) VALUES (
      NEW.organization_id, 'ALIMTALK', v_recipient_phone, v_recipient_name, v_recipient_profile_id,
      auth.uid(), 'PENDING', v_template.kakao_template_code, v_variables,
      NEW.schedule_id, NEW.program_id, 'LIVE', v_scheduled_send_at
    ) RETURNING notification_id INTO v_notification_id;

    -- pgmq 큐에 추가
    PERFORM pgmq.send(
      queue_name => 'alimtalk'::text,
      msg => jsonb_build_object(
        'notification_id', v_notification_id,
        'template_code', v_template.kakao_template_code,
        'recipient_phone', v_recipient_phone,
        'variables', v_variables,
        'send_mode', 'LIVE',
        'is_immediate', NOT v_is_batch_period,
        'scheduled_send_at', v_scheduled_send_at
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

/**
 * 수강생/관리자 취소 알림 트리거
 * - 수강생이 취소하면 관리자에게 (STD_CANCEL_ADMIN) - 즉시 발송
 * - 관리자가 취소하면 수강생에게 (ADM_CANCEL_STUDENT) - 하이브리드 발송
 */
CREATE OR REPLACE FUNCTION on_schedule_delete()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET SEARCH_PATH = ''
AS $$
DECLARE
  v_is_student BOOLEAN;
  v_template_type TEXT;
  v_template RECORD;
  v_recipient_phone TEXT;
  v_recipient_name TEXT;
  v_recipient_profile_id UUID;
  v_admin_phone TEXT;
  v_admin_profile_id UUID;
  v_org_name TEXT;
  v_program_title TEXT;
  v_variables JSONB;
  v_notification_id BIGINT;
  v_is_batch_period BOOLEAN;
  v_scheduled_send_at TIMESTAMPTZ;
  v_current_hour INT;
BEGIN
  -- 반복 일정 인스턴스는 원본만 처리
  IF OLD.parent_schedule_id IS NOT NULL THEN
    RETURN OLD;
  END IF;

  -- 삭제자가 수강생인지 확인
  v_is_student := OLD.student_id = auth.uid();

  IF v_is_student THEN
    -- 수강생이 직접 취소 → 관리자에게 알림
    v_template_type := 'STD_CANCEL_ADMIN';
  ELSE
    -- 관리자가 취소 → 수강생에게 알림
    v_template_type := 'ADM_CANCEL_STUDENT';
  END IF;

  -- 템플릿 설정 조회
  SELECT
    st.kakao_template_code,
    st.content,
    COALESCE(ot.status, 'ACTIVE') as status,
    COALESCE(ot.send_timing, st.default_timing) as send_timing,
    COALESCE(ot.scheduled_send_time, '09:00'::TIME) as scheduled_send_time,
    COALESCE(ot.batch_start_hour, 23) as batch_start_hour
  INTO v_template
  FROM public.super_templates st
  LEFT JOIN public.organization_templates ot
    ON st.super_template_id = ot.super_template_id
    AND ot.organization_id = OLD.organization_id
  WHERE st.type = v_template_type
    AND st.status = 'ACTIVE';

  -- 템플릿이 비활성화면 스킵
  IF v_template IS NULL OR v_template.status != 'ACTIVE' THEN
    RETURN OLD;
  END IF;

  -- 조직명 조회
  SELECT name INTO v_org_name
  FROM public.organizations
  WHERE organization_id = OLD.organization_id;

  -- 프로그램명 조회
  IF OLD.program_id IS NOT NULL THEN
    SELECT title INTO v_program_title
    FROM public.programs
    WHERE program_id = OLD.program_id;
  END IF;

  IF v_is_student THEN
    -- 수강생 정보 조회 (지역 정보 포함)
    SELECT
      CASE
        WHEN region IS NOT NULL AND region != '' THEN name || '(' || region || ')'
        ELSE name
      END,
      phone
    INTO v_recipient_name, v_recipient_phone
    FROM public.profiles
    WHERE profile_id = OLD.student_id;

    -- 관리자 전화번호 조회 (첫 번째 관리자)
    SELECT p.profile_id, p.phone INTO v_admin_profile_id, v_admin_phone
    FROM public.organization_members om
    JOIN public.profiles p ON p.profile_id = om.profile_id
    WHERE om.organization_id = OLD.organization_id
      AND om.role = 'ADMIN'
      AND om.state = 'NORMAL'
      AND p.phone IS NOT NULL
    LIMIT 1;

    -- 관리자 전화번호가 없으면 스킵
    IF v_admin_phone IS NULL THEN
      RETURN OLD;
    END IF;

    -- 변수 설정
    v_variables := jsonb_build_object(
      'organization_name', v_org_name,
      'program_title', COALESCE(v_program_title, '미지정'),
      'schedule_datetime', to_char(OLD.start_time AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI'),
      'student_name', v_recipient_name
    );

    -- notifications 생성 (즉시 발송)
    INSERT INTO public.notifications (
      organization_id, type, recipient_phone, recipient_name, recipient_profile_id,
      sender_profile_id, alimtalk_status, alimtalk_template_code, alimtalk_variables,
      schedule_id, program_id, send_mode
    ) VALUES (
      OLD.organization_id, 'ALIMTALK', v_admin_phone, NULL, v_admin_profile_id,
      OLD.student_id, 'PENDING', v_template.kakao_template_code, v_variables,
      OLD.schedule_id, OLD.program_id, 'LIVE'
    ) RETURNING notification_id INTO v_notification_id;

    -- pgmq 큐에 추가
    PERFORM pgmq.send(
      queue_name => 'alimtalk'::text,
      msg => jsonb_build_object(
        'notification_id', v_notification_id,
        'template_code', v_template.kakao_template_code,
        'recipient_phone', v_admin_phone,
        'variables', v_variables,
        'send_mode', 'LIVE',
        'is_immediate', true
      )
    );

  ELSE
    -- 관리자가 취소 → 수강생에게 알림 (하이브리드)
    -- 수강생 정보 조회
    SELECT p.name, p.phone, p.profile_id INTO v_recipient_name, v_recipient_phone, v_recipient_profile_id
    FROM public.profiles p
    WHERE p.profile_id = OLD.student_id;

    -- 수강생 전화번호가 없으면 스킵
    IF v_recipient_phone IS NULL THEN
      RETURN OLD;
    END IF;

    -- 변수 설정
    v_variables := jsonb_build_object(
      'organization_name', v_org_name,
      'program_title', COALESCE(v_program_title, '미지정'),
      'schedule_datetime', to_char(OLD.start_time AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI'),
      'student_name', v_recipient_name
    );

    -- 배치 구간 판단 (예: 23시~9시)
    v_current_hour := EXTRACT(HOUR FROM NOW() AT TIME ZONE 'Asia/Seoul');
    v_is_batch_period := (
      v_current_hour >= v_template.batch_start_hour OR
      v_current_hour < EXTRACT(HOUR FROM v_template.scheduled_send_time)
    );

    -- scheduled_send_at 계산
    IF v_is_batch_period THEN
      IF v_current_hour >= v_template.batch_start_hour THEN
        v_scheduled_send_at := (CURRENT_DATE + INTERVAL '1 day')::DATE + v_template.scheduled_send_time;
      ELSE
        v_scheduled_send_at := CURRENT_DATE::DATE + v_template.scheduled_send_time;
      END IF;
    ELSE
      v_scheduled_send_at := NULL;
    END IF;

    -- notifications 생성
    INSERT INTO public.notifications (
      organization_id, type, recipient_phone, recipient_name, recipient_profile_id,
      sender_profile_id, alimtalk_status, alimtalk_template_code, alimtalk_variables,
      schedule_id, program_id, send_mode, scheduled_send_at
    ) VALUES (
      OLD.organization_id, 'ALIMTALK', v_recipient_phone, v_recipient_name, v_recipient_profile_id,
      auth.uid(), 'PENDING', v_template.kakao_template_code, v_variables,
      OLD.schedule_id, OLD.program_id, 'LIVE', v_scheduled_send_at
    ) RETURNING notification_id INTO v_notification_id;

    -- pgmq 큐에 추가
    PERFORM pgmq.send(
      queue_name => 'alimtalk'::text,
      msg => jsonb_build_object(
        'notification_id', v_notification_id,
        'template_code', v_template.kakao_template_code,
        'recipient_phone', v_recipient_phone,
        'variables', v_variables,
        'send_mode', 'LIVE',
        'is_immediate', NOT v_is_batch_period,
        'scheduled_send_at', v_scheduled_send_at
      )
    );
  END IF;

  RETURN OLD;
END;
$$;

/**
 * 상담 신청 시 관리자에게 알림 트리거
 */
CREATE OR REPLACE FUNCTION on_consult_request_insert()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET SEARCH_PATH = ''
AS $$
DECLARE
  v_template RECORD;
  v_admin_phone TEXT;
  v_admin_profile_id UUID;
  v_org_name TEXT;
  v_program_title TEXT;
  v_variables JSONB;
  v_notification_id BIGINT;
BEGIN
  -- 상담 신청 타입만 처리
  IF NEW.type != 'CONSULT_REQUEST' THEN
    RETURN NEW;
  END IF;

  -- 템플릿 설정 조회
  SELECT
    st.kakao_template_code,
    COALESCE(ot.status, 'ACTIVE') as status
  INTO v_template
  FROM public.super_templates st
  LEFT JOIN public.organization_templates ot
    ON st.super_template_id = ot.super_template_id
    AND ot.organization_id = NEW.organization_id
  WHERE st.type = 'SYS_CONSULT_ADMIN'
    AND st.status = 'ACTIVE';

  -- 템플릿이 비활성화면 스킵
  IF v_template IS NULL OR v_template.status != 'ACTIVE' THEN
    RETURN NEW;
  END IF;

  -- 조직명 조회
  SELECT name INTO v_org_name
  FROM public.organizations
  WHERE organization_id = NEW.organization_id;

  -- 프로그램명 조회
  IF NEW.program_id IS NOT NULL THEN
    SELECT title INTO v_program_title
    FROM public.programs
    WHERE program_id = NEW.program_id;
  END IF;

  -- 관리자 전화번호 조회 (첫 번째 관리자)
  SELECT p.profile_id, p.phone INTO v_admin_profile_id, v_admin_phone
  FROM public.organization_members om
  JOIN public.profiles p ON p.profile_id = om.profile_id
  WHERE om.organization_id = NEW.organization_id
    AND om.role = 'ADMIN'
    AND om.state = 'NORMAL'
    AND p.phone IS NOT NULL
  LIMIT 1;

  -- 관리자 전화번호가 없으면 스킵
  IF v_admin_phone IS NULL THEN
    RETURN NEW;
  END IF;

  -- 변수 설정
  v_variables := jsonb_build_object(
    'organization_name', v_org_name,
    'requester_name', NEW.recipient_name,
    'requester_phone', NEW.recipient_phone,
    'program_title', COALESCE(v_program_title, '미지정'),
    'consult_message', COALESCE(NEW.consult_message, '')
  );

  -- 알림톡용 notifications 생성 (관리자에게)
  INSERT INTO public.notifications (
    organization_id, type, recipient_phone, recipient_name, recipient_profile_id,
    alimtalk_status, alimtalk_template_code, alimtalk_variables, program_id, send_mode
  ) VALUES (
    NEW.organization_id, 'ALIMTALK', v_admin_phone, NULL, v_admin_profile_id,
    'PENDING', v_template.kakao_template_code, v_variables, NEW.program_id, 'LIVE'
  ) RETURNING notification_id INTO v_notification_id;

  -- pgmq 큐에 추가
  PERFORM pgmq.send(
    queue_name => 'alimtalk'::text,
    msg => jsonb_build_object(
      'notification_id', v_notification_id,
      'template_code', v_template.kakao_template_code,
      'recipient_phone', v_admin_phone,
      'variables', v_variables,
      'send_mode', 'LIVE',
      'is_immediate', true
    )
  );

  RETURN NEW;
END;
$$;

-- =============================================
-- Trigger 등록
-- =============================================

-- 예약 생성 트리거
CREATE TRIGGER on_schedule_insert_trigger
AFTER INSERT ON public.schedules
FOR EACH ROW
EXECUTE FUNCTION on_schedule_insert();

-- 예약 삭제 트리거
CREATE TRIGGER on_schedule_delete_trigger
BEFORE DELETE ON public.schedules
FOR EACH ROW
EXECUTE FUNCTION on_schedule_delete();

-- 상담 신청 트리거 (상담 신청이 notifications에 INSERT될 때)
CREATE TRIGGER on_consult_request_insert_trigger
AFTER INSERT ON public.notifications
FOR EACH ROW
WHEN (NEW.type = 'CONSULT_REQUEST')
EXECUTE FUNCTION on_consult_request_insert();
